'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'

type Story = { id:string; title:string; category:string; status:string; updated_at:string }

export default function AdminPage() {
  const router = useRouter(); const [stories,setStories]=useState<Story[]>([]); const [loading,setLoading]=useState(true)
  useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession(); if(!session){router.replace('/admin/login');return} const {data:editor}=await supabase.from('editor_users').select('user_id').eq('user_id',session.user.id).maybeSingle(); if(!editor){router.replace('/admin/login');return} const {data}=await supabase.from('articles').select('id,title,category,status,updated_at').order('updated_at',{ascending:false}); setStories((data||[]) as Story[]); setLoading(false)})()},[router])
  async function logout(){await supabase.auth.signOut();router.replace('/admin/login')}
  const published=stories.filter(s=>s.status==='published').length, drafts=stories.filter(s=>s.status==='draft').length
  return <main className="min-h-screen bg-[#eeeae1] text-ink"><header className="border-b border-black/10 bg-ivory"><div className="mx-auto flex h-[76px] max-w-[1400px] items-center justify-between px-5 md:px-8"><div><Link href="/" className="serif text-[27px] font-bold tracking-[-.045em]">INK VERDE</Link><span className="ml-4 text-[9px] font-bold tracking-[.16em] text-verde">EDITORIAL STUDIO</span></div><div className="flex gap-5"><Link href="/" className="text-[10px] font-bold tracking-[.13em]">VIEW SITE ↗</Link><button onClick={logout} className="text-[10px] font-bold tracking-[.13em]">LOG OUT</button></div></div></header><div className="mx-auto max-w-[1400px] px-5 py-10 md:px-8 md:py-14"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow text-verde">NEWSROOM</p><h1 className="serif mt-2 text-[52px] leading-none tracking-[-.05em]">Good morning, editor.</h1><p className="mt-3 text-sm text-black/55">Write, edit and prepare the next story for Ink Verde.</p></div><Link href="/admin/new" className="w-fit bg-verde px-5 py-3 text-[10px] font-bold tracking-[.13em] text-ivory">+ NEW STORY</Link></div><div className="mt-10 grid gap-4 md:grid-cols-3"><div className="bg-ivory p-6"><p className="eyebrow text-black/45">PUBLISHED</p><p className="serif mt-2 text-4xl">{published}</p></div><div className="bg-ivory p-6"><p className="eyebrow text-black/45">DRAFTS</p><p className="serif mt-2 text-4xl">{drafts}</p></div><div className="bg-ivory p-6"><p className="eyebrow text-black/45">SECTIONS</p><p className="serif mt-2 text-4xl">06</p></div></div><section className="mt-12 bg-ivory"><div className="border-b border-black/10 px-6 py-5"><p className="eyebrow">STORIES</p></div>{loading?<p className="p-6 text-sm text-black/50">Loading newsroom…</p>:<div className="divide-y divide-black/10">{stories.map(story=><div key={story.id} className="grid gap-2 px-6 py-5 md:grid-cols-[1fr_150px_100px] md:items-center"><div><p className="eyebrow text-verde">{story.category}</p><p className="serif mt-1 text-xl">{story.title}</p></div><span className="text-[10px] font-bold tracking-[.1em] text-black/45">{story.status.toUpperCase()}</span><Link href={`/admin/edit/${story.id}`} className="text-[10px] font-bold tracking-[.1em] underline">EDIT</Link></div>)}</div>}</section></div></main>
}
