'use client'

import Link from 'next/link'
import { useState } from 'react'

export default function NewStoryPage() {
  const [title, setTitle] = useState('')
  const [dek, setDek] = useState('')
  const [category, setCategory] = useState('WORLD')
  const [body, setBody] = useState('')
  const [saved, setSaved] = useState(false)
  const saveDraft = () => { const current = JSON.parse(localStorage.getItem('ink-verde-drafts') || '[]'); current.push({ title, dek, category, body, savedAt: new Date().toISOString() }); localStorage.setItem('ink-verde-drafts', JSON.stringify(current)); setSaved(true) }
  return <main className="min-h-screen bg-[#eeeae1] text-ink"><header className="border-b border-black/10 bg-ivory"><div className="mx-auto flex h-[76px] max-w-[1200px] items-center justify-between px-5 md:px-8"><Link href="/admin" className="serif text-[27px] font-bold tracking-[-.045em]">INK VERDE</Link><Link href="/" className="text-[10px] font-bold tracking-[.13em]">VIEW SITE ↗</Link></div></header><div className="mx-auto max-w-[900px] px-5 py-10 md:px-8 md:py-16"><Link href="/admin" className="text-[10px] font-bold tracking-[.12em]">← NEWSROOM</Link><p className="eyebrow mt-10 text-verde">NEW STORY</p><h1 className="serif mt-2 text-[50px] leading-none tracking-[-.05em]">Write the next story.</h1><div className="mt-10 space-y-7 bg-ivory p-6 md:p-10"><label className="block"><span className="eyebrow">SECTION</span><select value={category} onChange={e=>setCategory(e.target.value)} className="mt-2 w-full border-b border-black/20 bg-transparent py-3 text-sm outline-none">{['WORLD','ECONOMY','CLIMATE','TECHNOLOGY','AFRICA','IDEAS'].map(x=><option key={x}>{x}</option>)}</select></label><label className="block"><span className="eyebrow">HEADLINE</span><input value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 w-full border-b border-black/20 bg-transparent py-3 font-serif text-3xl outline-none" placeholder="Write a strong headline…" /></label><label className="block"><span className="eyebrow">DEK</span><textarea value={dek} onChange={e=>setDek(e.target.value)} rows={2} className="mt-2 w-full border-b border-black/20 bg-transparent py-3 text-base leading-6 outline-none" placeholder="One or two sentences that frame the story…" /></label><label className="block"><span className="eyebrow">STORY</span><textarea value={body} onChange={e=>setBody(e.target.value)} rows={16} className="mt-2 w-full border border-black/10 bg-white/50 p-4 text-[16px] leading-8 outline-none" placeholder="Start writing…" /></label><div className="flex flex-wrap items-center gap-3 border-t border-black/10 pt-6"><button onClick={saveDraft} className="bg-ink px-5 py-3 text-[10px] font-bold tracking-[.13em] text-ivory">SAVE DRAFT</button><button type="button" className="border border-black/20 px-5 py-3 text-[10px] font-bold tracking-[.13em]">PREVIEW</button>{saved && <span className="text-[11px] text-verde">Draft saved on this device.</span>}</div></div><p className="mt-5 text-[11px] leading-5 text-black/50">This is the first editorial-studio layer. Drafts are currently saved in your browser while the secure database connection is being wired in.</p></div></main>
}
